export const GET_RECIPES_BEGIN = 'GET_RECIPES_BEGIN'
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS'
export const GET_RECIPES_ERROR = 'GET_RECIPES_ERROR'

export const GET_RECIPE_DETAILS_BEGIN = 'GET_RECIPE_DETAILS_BEGIN'
export const GET_RECIPE_DETAILS_SUCCESS = 'GET_RECIPE_DETAILS_SUCCESS'
export const GET_RECIPE_DETAILS_ERROR = 'GET_RECIPE_DETAILS_ERROR'

export const ADD_TO_FAVORITES_BEGIN = 'ADD_TO_FAVORITES_BEGIN'
export const ADD_TO_FAVORITES_SUCCESS = 'ADD_TO_FAVORITES_SUCCESS'
export const ADD_TO_FAVORITES_ERROR = 'ADD_TO_FAVORITES_ERROR'

export const GET_FAVORITES_RECIPES_BEGIN = 'GET_FAVORITES_RECIPES_BEGIN'
export const GET_FAVORITES_RECIPES_SUCCESS = 'GET_FAVORITES_RECIPES_SUCCESS'
export const GET_FAVORITES_RECIPES_ERROR = 'GET_FAVORITES_RECIPES_ERROR'


export const ADD_COMMENT_BEGIN = 'ADD_COMMENT_BEGIN'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR'